# Use an official Node.js runtime as a parent image
FROM node:16-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY planner-react/package*.json /app

# Install dependencies
RUN yarn

# Copy the rest of the application files to the working directory
COPY ./planner-react /app

# Build the application
RUN npm run build

# Expose port 80
EXPOSE 80

# Set the command to run when the container starts
CMD ["npm", "run", "start"]
