version: "3.8"
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"

  express-server:
    build: 
      context: .
      dockerfile: Dockerfile-express
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: