version: "3.8"
services:

  flask-server:
    build: 
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: party-pp-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminsecret

volumes:
  mongodb-data: