version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: party-pp-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminsecret
      - JWT_SECRET_KEY=jwtsecretkey

volumes:
  mongodb-data: