
import { createSlice } from '@reduxjs/toolkit'

/**
* A Redux slice that contains the initial session state and reducers to modify it.
*/
export const vendorSlice = createSlice({
    name: 'vendor',
    initialState: {
        usvendorer: JSON.parse(localStorage.getItem("planner-pp-vendor")) || null,
    },
    reducers: {
        setVendor: (state, action) => {
            // Redux Toolkit allows us to write "mutating" logic in reducers. It
            // doesn't actually mutate the state because it uses the immer library,
            // which detects changes to a "draft state" and produces a brand new
            // immutable state based off those changes
            const payload = action.payload
            const vendorData = {
                id: payload._id.$oid,
                name: payload.name,
                email: payload.email,
                address: payload.address,
                zipcode: payload.zipcode,
                vendorType: payload.vendorType,
                operatorIds: payload.operator_ids,
                rating: payload.rating,
                ratingCount: payload.rating_count,
                services: payload.services
            }
            state.vendor = vendorData
            localStorage.setItem("planner-pp-vendor", JSON.stringify(vendorData))
        },
        clearVendor: (state) => {
            state.vendor = null
            localStorage.removeItem("planner-pp-vendor")
        }
    }
})

// Actions generated by the reducers
export const { setVendor, clearVendor } = vendorSlice.actions

// The functions below are called selectors and allows us to select values from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state) => state.counter.value)`
/**
Selectors to retrieve specific data from the session state.
These selectors can be used with the useSelector hook to retrieve the desired data.
*/
export const selectVendor = (state) => state.vendor.vendor

// The reducer function generated by the slice
export default vendorSlice.reducer